# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: FTP Browser
version: "1.0.0"
icon: icon.png
slug: ftp_client
description: Simple FTP Client to browes files on a FTP server.
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
